---
- bacon:
    description: Smoked, thinly sliced pork belly
    tags:
    - meat
    season: all
- asparagus:
    description: a spring vegetable, native to most of Europe, northern Africa and
      western Asia
    tags:
    - vegetable
    season: spring
- flour:
    description: a powder made by grinding cereal grains, other seeds or roots
    tags:
    - gluten
    season: all
- beer:
    description: the world's most loved alcoholic beverage
    tags:
    - alcohol
    season: all
- bamboo:
    description: the largest members of the grass family, and some of the fastest
      growing plants in the world
    tags:
    - Asian
    - vegetable
    season: all
- beans:
    description: large plant seeds of several genera of the family Leguminosae
    tags:
    - pulse
    season: summer
- lentils:
    description: an edible pulse
    tags:
    - pulse
    season: summer
- peas:
    description: an edible pulse
    tags:
    - pulse
    season: summer
- beef:
    description: meat from domestic cattle
    tags:
    - meat
    - red meat
    season: all
- veal:
    description: meat from infant domestic cattle
    tags:
    - meat
    - red meat
    season: all
- pork:
    description: meat from domestic pigs
    tags:
    - meat
    - white meat
    season: all
- mushrooms:
    description: the fleshy body of a fungus
    tags:
    - fungus
    - vegetarian
    season: all
- cod:
    description: salt water fish with a mild flavour and a dense, flaky white flesh
    tags:
    - fish
    season: all
- vinegar:
    description: acetic acid diluted in water
    tags:
    - acid
    - slow cooking
    season: all
- bok choy:
    description: Chinese cabbage
    tags:
    - green
    - Chinese
    - vegetable
    season: all
- garlic:
    description: pungent flavored bulb related to onions
    tags:
    - vegetable
    - smelly
    season: all
- onions:
    description: the most widely cultivated species of the genus Allium
    tags:
    - vegetable
    season: all
- chicken:
    description: the most common type of poultry in the world
    energy: 916000
    tags:
    - poultry
    - meat
    - white meat
    season: all
- icecream:
    description: Cold, creamy and delicious.  Comes in various flavours
    tags:
    - cold
    - sweet
    - dessert
    season: all
- pastry:
    description: The dough from which baked products are made
    tags:
    - gluten
    - baking
    season: all
- sugar:
    description: a sweet carbohydrate
    tags:
    - sweet
    - carbohydrate
    - glucose
    - fructose
    - galactose
    season: all
- honey:
    description: A sweet food made by bees using nectar from flowers
    tags:
    - sweet
    - fructose
    - glucose
    season: all
- maple syrup:
    description: A syrup usually made from the xylem sap of Maple trees
    tags:
    - maple
    - sap
    - syrup
    - sweet
    season: all
- molasses:
    description: Sweet, viscous by-product of the beating of sugarcane, grapes or
      sugar beets into sugar
    tags:
    - sweet
    season: all
- toffee:
    description: Sweet confenction made by caramelizing sugar or molasses (creating
      inverted sugar) along with butter, and occasionally flour
    tags:
    - sweet
    - carbohydrate
    - glucose
    - fructose
    - galactose
    season: all
- cinnamon:
    description: A spice obtained from the inner bark of several trees from the genus
      Cinnamomum, native to Sri Lanka, that is used in both sweet and savoury foods.
    tags:
    - Sri Lanka
    - spice
    season: all
- ginger:
    description: The rhizome of the plant Zingiber officinale, consumed as a delicacy,
      medicine, or spice.
    tags:
    - spice
    - Asian
    season: all
- cardamom:
    description: Several plants of the similar genera Elettaria and Amomum in the
      ginger family Zingiberaceae
    tags:
    - India
    - Bhutan
    - Nepal
    - spice
    season: all
- nutmeg:
    description: A spice made from Myristica fragrans, an evergreen tree indigenous
      to the Banda Islands in the Moluccas (or Spice Islands) of Indonesia.
    tags:
    - spice
    - Indonesia
    season: all
- salt:
    description: 
    tags: []
    season: all
- cocoa:
    description: A low-fat component of chocolate, extracted from cocoa beans
    tags:
    - chocolate
    season: all
- milk:
    description: A white liquid produced by the mammary glands of mammals
    tags:
    - white
    - liquid
    - dairy
    season: all
- butter:
    description: A dairy product made by churning fresh or fermented cream or milk
    tags:
    - dairy
    - spread
    - oil
    season: all
- oil:
    description: A fat obtained from animals or vegetables, or from drilling for oil
    tags:
    - oil
    season: all
- nuts:
    description: Hard-shelled indehiscent fruits of some plants
    tags:
    - seed
    season: all
- walnuts:
    description: An edible seed of any tree of the genus Juglans, especially the Persian
      walnut, Juglans regia
    tags:
    - nut
    - seed
    season: all
- pecans:
    description: Carya illinoinensis, is a species of hickory, native to south-central
      North America, in Mexico from Coahuila south to Jalisco and Veracruz
    tags:
    - America
    - USA
    - Mexico
    - nut
    season: all
- almonds:
    description: The edible and widely cultivated seed of the Prunus dulcis tree
    tags:
    - Middle East
    - nut
    season: all
- pistachios:
    description: Seeds from the Pistacia vera tree
    tags:
    - Middle East
    - USA
    - Turkey
    - nut
    season: all
- dried fruit:
    description: Fruit where the majority of the original water content has been removed
      either naturally, through sun drying, or through the use of specialized dryers
      or dehydrators
    tags:
    - fruit
    - dried
    - dehydrated
    season: all
- oats:
    description: Oats are a cerial
    tags:
    - oat
    - cerial
    - grain
    season: all
- sultanas:
    description: A delicious dried grape
    tags:
    - grape
    - fruit
    season: all
- figs:
    description: A delicious fruit
    tags:
    - fig
    - fruit
    season: all
- seeds:
    description: Edible seeds from various plants
    tags:
    - seed
    season: all
- zucchini:
    description: The zucchini or courgette is a dark o rlight green summer squash
      which can reach nearly a meter in length, but which is usually harvested at
      half that size or less
    tags:
    - green
    - vegetable
    - squash
    season: all
- eggs:
    description: Typically refers to Chicken Eggs which and have been eaten by humans
      for millennia
    tags:
    - egg
    - chicken
    season: all
- duck eggs:
    description: Eggs laid by ducks. Larger and fattier than chicken eggs
    tags:
    - egg
    - duck
    season: all
- pepper:
    description: The genus Piper (genus) of the pepper family (Piperaceae)
    tags:
    - spice
    season: all
- cream:
    description: Cream is a dairy product that is composed of the higher-butterfat layer skimmed from the top of milk before homogenization.
    tags:
    - dairy
    season: all
- liquid nitrogen:
    description: Liquid nitrogen is nitrogen in a liquid state at an extremely low temperature.
    season: all
    tags:
    - cold
- yoghurt:
    description: A dairy product produced by bacterial fermentation of milk.
    season: all
    tags:
    - diary
