# SQLite version 3.x
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 10
  timeout: 5000

# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# This will be overwritten when being pushed to Heroku
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
