---
- a pinch of salt:
    description: A small amount of salt
    core_ingredient: salt
- a whole fish:
    description: 
    core_ingredient: fish
- almonds:
    description: The edible and widely cultivated seed of the Prunus dulcis tree
    core_ingredient: almonds
- apple cider vinegar:
    description: acetic acid diluted in water
    core_ingredient: vinegar
- asparagus:
    description: a spring vegetable, native to most of Europe, northern Africa and
      western Asia
    core_ingredient: asparagus
- bacon:
    description: Smoked, thinly sliced pork belly
    core_ingredient: bacon
- bacon rashers:
    description: 
    core_ingredient: bacon
- baked beans:
    description: an edible pulse
    core_ingredient: beans
- balsamic vinegar:
    description: dark brown, aromatic, aged type of vinegar
    core_ingredient: vinegar
    tags:
    - Italian
    - traditional
- bamboo:
    description: the largest members of the grass family, and some of the fastest
      growing plants in the world
    core_ingredient: bamboo
- beans:
    description: large plant seeds of several genera of the family Leguminosae
    core_ingredient: beans
- beef:
    description: meat from domestic cattle
    core_ingredient: beef
- beer:
    description: the world's most loved alcoholic beverage
    core_ingredient: beer
- black eyed peas:
    description: an edible pulse
    core_ingredient: peas
- black pepper:
    description: The dried fruit of the Piper nigrum vine
    core_ingredient: pepper
- bleached flour:
    description: any refined flour with a whitening agent added
    core_ingredient: flour
- bok choy:
    description: Chinese cabbage
    core_ingredient: bok choy
- breadcrumbs:
    description: 
    core_ingredient: breadcrumbs
- broad beans:
    description: an edible pulse
    core_ingredient: beans
- brown sugar:
    description: Unrefined or partially refined soft sugar with residual molasses
      content
    core_ingredient: sugar
    tags:
    - molasses
- butter:
    description: A dairy product made by churning fresh or fermented cream or milk
    core_ingredient: butter
- cardamom:
    description: Several plants of the similar genera Elettaria and Amomum in the
      ginger family Zingiberaceae
    core_ingredient: cardamom
- cardamom pod:
    description: The whole seeds of a cardamom plant
    core_ingredient: cardamom
    tags:
    - seed
- cauliflower florets:
    description: 
    core_ingredient: cauliflower
- cheese:
    description: 
    core_ingredient: cheese
- chicken:
    description: the most common type of poultry in the world
    core_ingredient: chicken
- chicken livers:
    description: the livers of a chicken
    core_ingredient: chicken
- chicken stock:
    description: 
    core_ingredient: chicken stock
    tags:
    - poultry
    - meat
    - white meat
- chicken thighs:
    description: the most common type of poultry in the world
    core_ingredient: chicken
- chicken wings:
    description: the wings of a chicken
    core_ingredient: chicken
- chickpeas:
    description: 
    core_ingredient: chickpeas
- cinnamon:
    description: A spice obtained from the inner bark of several trees from the genus
      Cinnamomum, native to Sri Lanka, that is used in both sweet and savoury foods.
    core_ingredient: cinnamon
- cocoa powder:
    description: A low-fat component of chocolate, extracted from cocoa beans
    core_ingredient: cocoa
- cod:
    description: salt water fish with a mild flavour and a dense, flaky white flesh
    core_ingredient: cod
- condensed milk:
    description: Cow's milk from which water has been removed.
    core_ingredient: milk
    tags:
    - sweet
    - viscous
- cream:
    description: Cream is a dairy product that is composed of the higher-butterfat
      layer skimmed from the top of milk before homogenization.
    core_ingredient: cream
- curry powder:
    description: A mixture of spices of widely varying composition based on South Asian cuisine.
    core_ingredient: curry
- diced carrots:
    description: Carrots cut into small cubes.
    core_ingredient: carrot
- dried fruit:
    description: Fruit where the majority of the original water content has been removed
      either naturally, through sun drying, or through the use of specialized dryers
      or dehydrators
    core_ingredient: dried fruit
- drumsticks:
    description: the legs of a chicken
    core_ingredient: chicken
- duck eggs:
    description: Eggs laid by ducks. Larger and fattier than chicken eggs
    core_ingredient: duck eggs
- echidna:
    description: 
- eggs:
    description: Typically refers to Chicken Eggs which and have been eaten by humans
      for millennia
    core_ingredient: eggs
- figs:
    description: Fruit of the Ficus carica tree
    core_ingredient: figs
- filo pastry:
    description: Delicate and flaky, Filo pastry is paper-thin pastry dough and used
      in layers, is generally wrapped around a filling and brushed with butter before
      baking
    core_ingredient: pastry
    tags:
    - Greek
- fish:
    description: 
    core_ingredient: fish
- flaky pastry:
    description: Flaky pastry is a simple pastry that expands when cooked due to the
      number of layers. It bakes into a crisp, buttery pastry
    core_ingredient: pastry
- flour:
    description: a powder made by grinding cereal grains, other seeds or roots
    core_ingredient: flour
- garlic:
    description: pungent flavored bulb related to onions
    core_ingredient: garlic
- ginger:
    description: The rhizome of the plant Zingiber officinale, consumed as a delicacy,
      medicine, or spice.
    core_ingredient: ginger
- honey:
    description: A sweet food made by bees using nectar from flowers
    core_ingredient: honey
- icecream:
    description: Cold, creamy and delicious.  Comes in various flavours
    core_ingredient: icecream
- icing sugar:
    description: Very fine sugar that typically contains a small amount of anti-caking
      agent
    core_ingredient: sugar
    tags:
    - powder
- kampot pepper:
    description: A black pepper local to Kampot Province in Cambodia
    core_ingredient: pepper
    tags:
    - Asian
    - Cambodia
- kangaroo:
    description: 
- kidney beans:
    description: an edible pulse
    core_ingredient: beans
- lamb shoulder:
    description: 
    core_ingredient: lamb
- lentils:
    description: an edible pulse
    core_ingredient: lentils
- lettuce:
    description: 
- lima beans:
    description: an edible pulse
    core_ingredient: beans
- liquid nitrogen:
    description: Liquid nitrogen is nitrogen in a liquid state at an extremely low
      temperature.
    core_ingredient: liquid nitrogen
- maple syrup:
    description: A syrup usually made from the xylem sap of Maple trees
    core_ingredient: maple syrup
- milk:
    description: A white liquid produced by the mammary glands of mammals
    core_ingredient: milk
- molasses:
    description: Sweet, viscous by-product of the beating of sugarcane, grapes or
      sugar beets into sugar
    core_ingredient: molasses
- mung beans:
    description: an edible pulse
    core_ingredient: beans
- mushrooms:
    description: the fleshy body of a fungus
    core_ingredient: mushrooms
- natural yoghurt:
    description: 
    core_ingredient: yoghurt
- nutmeg:
    description: A spice made from Myristica fragrans, an evergreen tree indigenous
      to the Banda Islands in the Moluccas (or Spice Islands) of Indonesia.
    core_ingredient: nutmeg
- nuts:
    description: Hard-shelled indehiscent fruits of some plants
    core_ingredient: nuts
- olive oil:
    description: A fat obtained from olives
    core_ingredient: oil
    tags:
    - olive
    - Mediterranean
    - Greek
    - Italian
- onions:
    description: the most widely cultivated species of the genus Allium
    core_ingredient: onions
- palm sugar:
    description: Sugar made from the sap of the Palmyra palm, the date palm, the sugar
      date palm, the sago palm or the arenga pinnata, aka sugar palm.
    core_ingredient: sugar
    tags:
    - Thai
    - Asian
- pastry:
    description: The dough from which baked products are made
    core_ingredient: pastry
- peanut oil:
    description: A mild tasting vegetable oil derived from peanuts
    core_ingredient: oil
    tags:
    - peanut
    - frying
- peas:
    description: an edible pulse
    core_ingredient: peas
- pecans:
    description: Carya illinoinensis, is a species of hickory, native to south-central
      North America, in Mexico from Coahuila south to Jalisco and Veracruz
    core_ingredient: pecans
- pistachios:
    description: Seeds from the Pistacia vera tree
    core_ingredient: pistachios
- plain flour:
    description: flour that does not have a leavening agent. Aka all-purpose flour
    core_ingredient: flour
- poppy seeds:
    description: Kydney-shaped oilseed obtained from the opium poppy (Papaver somniferum)
    core_ingredient: seeds
    tags:
    - opium
- pork:
    description: meat from domestic pigs
    core_ingredient: pork
- puff pastry:
    description: Puff pastry has many layers that cause it to expand or “puff” when
      baked. Pastries are made using flour, butter, salt, and water. Pastry rises
      up due to the combination and reaction of the four ingredients and also from
      the air that gets between the layers
    core_ingredient: pastry
- puy lentils:
    description: an edible pulse
    core_ingredient: lentils
- red lentils:
    description: an edible pulse
    core_ingredient: lentils
- red onions:
    description: medium to large sized onions with a mild to sweet flavor
    core_ingredient: onions
- refined flour:
    description: flour that has had the germ and bran removed. Typically referred
      to as "white flour"
    core_ingredient: flour
- rolled oats:
    description: Oat groats that have been rolled into flat flakes under heavy rollers
      and then steamed and lightly toasted
    core_ingredient: oats
- rosemary:
    description: 
    core_ingredient: rosemary
- runner beans:
    description: an edible pulse
    core_ingredient: beans
- sage:
    description: 
    core_ingredient: sage
- salt:
    description: 
    core_ingredient: salt
- self raising flour:
    description: flour sold premixed with chemical leavening agents
    core_ingredient: flour
- sesame seeds:
    description: Sesame seed is considered to be the oldest oilseed crop known to
      man, domesticated well over 5000 years ago
    core_ingredient: seeds
    tags:
    - oil
- shortcrust pastry:
    description: Shortcrust, or short, pastry is the simplest and most common pastry.
      It is made with flour, fat, salt, and water. It is mainly used to make tarts
    core_ingredient: pastry
    tags:
    - tart
- slice of bread:
    description: 
    core_ingredient: bread
- sliced red onions:
    description: 
    core_ingredient: onions
- soy beans:
    description: an edible pulse
    core_ingredient: beans
- sprig of rosemary:
    description: 
    core_ingredient: rosemary
- sugar:
    description: a sweet carbohydrate
    core_ingredient: sugar
- sultanas:
    description: Sultana raisins are small, sweet and have a golden colour
    core_ingredient: sultanas
- sumac:
    description: 
    core_ingredient: sumac
- sunflower oil:
    description: A non-volatile oil expressed from sunflower (Helianthus annuus) seeds
    core_ingredient: oil
    tags:
    - sunflower
    - frying
    - triglyceride
- sunflower seeds:
    description: The fruit of the sunflower (Helianthus annuus)
    core_ingredient: seeds
    tags:
    - sunflower
    - oil
- toffee:
    description: Sweet confenction made by caramelizing sugar or molasses (creating
      inverted sugar) along with butter, and occasionally flour
    core_ingredient: toffee
- tomato:
    description: 
- tumeric:
    description: 
- unbleached flour:
    description: flour that has not undergone bleaching and therefore does not have
      the color of "white" flour
    core_ingredient: flour
- veal:
    description: meat from infant domestic cattle
    core_ingredient: veal
- veal fillets:
    description: 
    core_ingredient: veal
- vinegar:
    description: acetic acid diluted in water
    core_ingredient: vinegar
- walnuts:
    description: An edible seed of any tree of the genus Juglans, especially the Persian
      walnut, Juglans regia
    core_ingredient: walnuts
- water:
    description: 
- white pepper:
    description: White pepper consists of the seed of the pepper plant alone, with
      the darker coloured skin of the pepper fruit removed.
    core_ingredient: pepper
- white sugar:
    description: Refined sugar.
    core_ingredient: sugar
- white vinegar:
    description: a colorless solution of acetic acid diluted in water
    core_ingredient: vinegar
- wine:
    description: 
    core_ingredient: wine
- wine (red):
    description: 
    core_ingredient: wine
- wombat:
    description: 
- yoghurt:
    description: A dairy product produced by bacterial fermentation of milk.
    core_ingredient: yoghurt
- zucchini:
    description: The zucchini or courgette is a dark or light green summer squash
      which can reach nearly a meter in length, but which is usually harvested at
      half that size or less
    core_ingredient: zucchini
- zucchini flowers:
    description: A golden blossom on the end of each emergent zucchini. The male flower
      grows directly on the stem of the zucchini plant in the leaf axils (where leaf
      petiole meets stem), on a long stalk, and is slightly smaller than the female.
      Both flowers are edible, and are often used to dress a meal or to garnish the
      cooked fruit
    core_ingredient: zucchini
    tags:
    - flower
