# if you add to this, also be sure to add to the translation files.

- chopped
- crushed
- cubed
- diced
- finely-chopped
- finely-sliced
- grated
- julienned
- melted
- powdered
- rinsed
- sliced
- soaked
- whole
